fix: improve session cleanup and progress handling
modelcontextprotocol/python-sdk pull request #85
Opened 2024-12-02 17:20 UTC by donghao1393

# Fix Server Crash During Progress Notification Cleanup

This PR fixes server crashes occurring during cleanup after completed requests. The issue was discovered and diagnosed through the Model Context Protocol OpenAI server implementation (see the screenshot).
![image](https://github.com/user-attachments/assets/32132631-7599-4252-80f7-4331adb8bee3)

## Issue
When a request completes successfully and progress notifications are involved, servers would crash during cleanup with validation errors for 'cancelled' notifications. This happens because:

1. Session cleanup sends an internal 'cancelled' notification
2. This notification fails validation against ProgressNotification schema
3. Validation error propagates and crashes the server

## Fix
- Add session state tracking with `_closed` flag
- Skip notification validation during cleanup phase
- Improve progress notification handling in context managers
- Add proper cleanup for progress notification context

## Testing
Verified fix using MCP OpenAI server implementation:
- Multiple consecutive image generation requests complete successfully
- No crashes during cleanup
- Progress notifications work reliably

## Credit
This issue was discovered and diagnosed through Claude (Anthropic) using the MCP OpenAI server implementation. The debugging process helped identify core cleanup issues in the SDK.

2024-12-05 14:07 UTC, donghao1393 commented
The issue also occurred with https://github.com/modelcontextprotocol/servers/tree/main/src/fetch. It was also resolved in this commit.
```
Installed 31 packages in 36ms
(node:61856) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Traceback (most recent call last):
  File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/anyio/streams/memory.py", line 242, in send
    self.send_nowait(item)
  File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/anyio/streams/memory.py", line 225, in send_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/server/__init__.py", line 467, in run
    await message.respond(
  File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/shared/session.py", line 58, in respond
    await self._session._send_response(
  File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/shared/session.py", line 196, in _send_response
    await self._write_stream.send(JSONRPCMessage(jsonrpc_error))
  File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/anyio/streams/memory.py", line 248, in send
    await send_event.wait()
  File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1747, in wait
    await self._event.wait()
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 103cd0650

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/server/stdio.py", line 83, in stdio_server
  |     yield read_stream, write_stream
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp_server_fetch/server.py", line 272, in serve
  |     await server.run(read_stream, write_stream, options, raise_exceptions=True)
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/server/__init__.py", line 423, in run
  |     async with ServerSession(
  |                ^^^^^^^^^^^^^^
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/shared/session.py", line 122, in __aexit__
  |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/shared/session.py", line 235, in _receive_loop
    |     notification = self._receive_notification_type.model_validate(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/pydantic/main.py", line 627, in model_validate
    |     return cls.__pydantic_validator__.validate_python(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | pydantic_core._pydantic_core.ValidationError: 5 validation errors for ClientNotification
ProgressNotification.method
  Input should be 'notifications/progress' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
ProgressNotification.params.progressToken
  Field required [type=missing, input_value={'requestId': 127, 'reaso... -2: Request timed out'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
ProgressNotification.params.progress
  Field required [type=missing, input_value={'requestId': 127, 'reaso... -2: Request timed out'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
InitializedNotification.method
  Input should be 'notifications/initialized' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
RootsListChangedNotification.method
  Input should be 'notifications/roots/list_changed' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
    +------------------------------------

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/bin/mcp-server-fetch", line 10, in <module>
  |     sys.exit(main())
  |              ^^^^^^
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp_server_fetch/__init__.py", line 20, in main
  |     asyncio.run(serve(args.user_agent, args.ignore_robots_txt))
  |   File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp_server_fetch/server.py", line 271, in serve
  |     async with stdio_server() as (read_stream, write_stream):
  |                ^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 231, in __aexit__
  |     await self.gen.athrow(value)
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/server/stdio.py", line 80, in stdio_server
  |     async with anyio.create_task_group() as tg:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp/server/stdio.py", line 83, in stdio_server
    |     yield read_stream, write_stream
    |   File "/Users/donghao/.cache/uv/archive-v0/CiVrAnivdRZCJwWmSC5l6/lib/python3.12/site-packages/mcp_server_fetch/server.py", line 272, in serve
    |     await server.run(read_stream [...]

2024-12-16 21:41 UTC, dsp-ant requested changes
Thank you for working on this. I think it's the right direction but needs a bit more refinement. If you don't mind taking a look at my requested changes. I think we are close to getting this in.

2024-12-16 21:41 UTC, dsp-ant commented on src/mcp/shared/session.py
> +            return False
I don't see how this can raise an exception and require a try block

2024-12-16 21:41 UTC, dsp-ant commented on src/mcp/shared/session.py
> +                                raise
I think any notification type must be validated, since it ensures that we have a proper pydantic model for the given notification.

What this section should do, is handle the cancellation notification and not forward it to the incoming_message_stream_writer.

2024-12-16 21:41 UTC, dsp-ant commented on src/mcp/shared/session.py
> +                getattr(message_root, "method", None) != "cancelled" and
Note that cancellation notification's method is called `notifications/cancelled`, see https://spec.modelcontextprotocol.io/specification/basic/utilities/cancellation/

2024-12-17 12:24 UTC, donghao1393 commented on src/mcp/shared/session.py
> +            return False
https://github.com/modelcontextprotocol/python-sdk/pull/85/commits/6c9ca12d32506ddf0e8ead4d216407f389fe432e

2024-12-17 12:24 UTC, donghao1393 commented on src/mcp/shared/session.py
> +                                raise
https://github.com/modelcontextprotocol/python-sdk/pull/85/commits/cffdd06464aaea90583847290376b4cc505cd6ca

2024-12-17 12:24 UTC, donghao1393 commented on src/mcp/shared/session.py
> +                getattr(message_root, "method", None) != "cancelled" and
https://github.com/modelcontextprotocol/python-sdk/pull/85/commits/e592afd7dba4066cfc115caed754e6b91927ed92

2024-12-17 12:25 UTC, donghao1393 commented
Hi @dsp-ant , thank you for your advice. I have made commit. Would you help to check again?

2025-01-03 16:44 UTC, donghao1393 commented
Technical Details
- The issue occurred when internal notifications were received during cleanup
- Added _closed flag to track session state accurately
- Modified notification handling to be cleanup-aware
- Ensures graceful shutdown even with pending notifications

Impact
- Prevents validation errors during shutdown
- Maintains session stability during cleanup
- No interference with normal operation
- Compatible with existing notification patterns

This approach keeps the fix focused on the core issue while maintaining 
backward compatibility.

2025-01-06 06:55 UTC, txbm commented
@dsp-ant @donghao1393 - if I may suggest a more straight-forward fix for this inline with codebase patterns? - https://github.com/txbm/python-sdk/commit/19185626d57fdd670219784d10859c7d0a302c2e

2025-01-06 15:06 UTC, donghao1393 commented
> @dsp-ant @donghao1393 - if I may suggest a more straight-forward fix for this inline with codebase patterns? - [txbm@1918562](https://github.com/txbm/python-sdk/commit/19185626d57fdd670219784d10859c7d0a302c2e)

I tested in my local and it's working. I think this is a better solution. What do you think @dsp-ant ?

2025-01-07 07:15 UTC, orliesaurus commented
Please can you merge this fix in, it's breaking my server on claude desktop app - thank you!

2025-01-18 14:44 UTC, jerome3o-anthropic requested changes
Hey @donghao1393 - It seems to me that this can be simplified a lot now that there is the canceled notification types.

I'm going to be doing a loop on notifications in this sdk soon, and for my understanding (and to write some tests) I'd love it if you could also provide an example that reproduces this issue? would it just be a server with a long running task and the client sending of a cancel notification?

2025-01-18 14:44 UTC, jerome3o-anthropic commented on src/mcp/shared/session.py
> +    def _is_cancellation_notification(self, message_root: JSONRPCNotification) -> bool:
This should no longer be needed now that there are the correct types defined

2025-01-18 14:44 UTC, jerome3o-anthropic commented on src/mcp/shared/session.py
> +                    if self._is_cancellation_notification(message.root):
Can this be significantly simplified now that we have the types defined?

2025-01-18 16:30 UTC, donghao1393 commented on src/mcp/shared/session.py
> +    def _is_cancellation_notification(self, message_root: JSONRPCNotification) -> bool:
Thanks for the suggestions. I share your instinct about simplifying the code based on types, but I have some concerns:

1. The cancellation notification we receive is actually using "cancelled" as the method name, not "notifications/cancelled". This is why we need the explicit check in `_is_cancellation_notification`.

2. Even with the type definitions, the runtime behavior might still need this handling because:
   - The notification comes from the transport layer before type validation
   - We need to handle both formats for backwards compatibility
   - The validation would fail before we can process the notification properly

Would it help if I add some comments explaining this in the code? Or would you prefer to first verify this with the test case I mentioned above?

2025-01-18 16:39 UTC, donghao1393 commented
> Hey @donghao1393 - It seems to me that this can be simplified a lot now that there is the canceled notification types.
> 
> I'm going to be doing a loop on notifications in this sdk soon, and for my understanding (and to write some tests) I'd love it if you could also provide an example that reproduces this issue? would it just be a server with a long running task and the client sending of a cancel notification?

Yes, you're right. A reproduction case would be a server with a long-running task (like image generation) that typically takes more than a few seconds, and the client sending a cancel notification during the process. I can provide a minimal example:

1. add this of [my mcp service](https://github.com/donghao1393/mcp-openai/blob/main/README.en.md#setup)
2. A client that initiates the task and sends a cancel notification, like:
    - 1st prompt "create an image using openai mcp service to depict a dog standing on the moon watching the earth"
    - 2nd prompt "create another image that the dog was running"
    - if the cancel notification made the service down in 1st prompt, the 2nd prompt would be failed to send request
4. inspect the log file `mcp-server-openai.log` so that we can observe the cancellation behavior

This would help validate both the current behavior and any proposed changes.

2025-02-05 17:43 UTC, donghao1393 commented on src/mcp/shared/session.py
> +    def _is_cancellation_notification(self, message_root: JSONRPCNotification) -> bool:
removed as no needed

2025-02-05 17:43 UTC, donghao1393 commented on src/mcp/shared/session.py
> +                    if self._is_cancellation_notification(message.root):
updated with code from https://github.com/modelcontextprotocol/python-sdk/pull/167

2025-02-05 17:44 UTC, donghao1393 commented
Hi @jerome3o-anthropic , I have updated accordingly and passed my test. Would you help to take a review for the next?

2025-02-11 18:16 UTC, orliesaurus commented
I am curious if you could merge this? @dsp-ant 
Maybe it will fix my issues with `The read operation timed out`

2025-02-11 19:15 UTC, donghao1393 commented
> It seem the issue is fixed, either Claude Desktop update or using the latest main branch. As already I see cancelled got added as valid type, so should no more throw panic error and crash.

I have tested without this PR, but it failed in my case.

2025-02-11 20:44 UTC, closed without merging

2025-02-11 20:44 UTC, donghao1393 commented
> I have used the main branch. It's not in 1.2.1. For me this seem solving it.
> 
> https://github.com/modelcontextprotocol/python-sdk/blob/f10665db4c2f676da1131617ad67715952258712/src/mcp/types.py#L995
> 
> 
> I testing 1 min task withtout issue when I moved using the new main branch. Previously would crash.
> I had even similar patch as your and removed it.
> Can you test the main branch not 1.2.1.

Thank you for your advice. I tried with
```
# disable old mcp sdk
uv add git+https://github.com/modelcontextprotocol/python-sdk --branch main
# restart claude desktop
```
And then it works.

2025-02-12 00:53 UTC, orliesaurus commented
> I have used the main branch. It's not in 1.2.1. For me this seem solving it.
> 
> https://github.com/modelcontextprotocol/python-sdk/blob/f10665db4c2f676da1131617ad67715952258712/src/mcp/types.py#L995
> 
> 
> I testing 1 min task withtout issue when I moved using the new main branch. Previously would crash.
> I had even similar patch as your and removed it.
> Can you test the main branch not 1.2.1.

if it's not in 1.2.1 is it going to be out in 1.2.2 or what's the logic you think?